#
# This file contains configuration variables for drivers.
# It was generated by genhdrs.pl. Do not modify it.
#
package Driverhdrs;

$LAB = "datalab";
$SERVER_NAME = "10.1.4.34";
$SERVER_PORT = 8081;
$COURSE_NAME = "ci0118";
$AUTOGRADE_TIMEOUT = 0;
1;
